FROM debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    e2fsprogs \
    gcovr \
    mandoc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

CMD ["/bin/sh"]
